### ISSUE TITLE
Null Problem

### ISSUE THREAD

**Issue by tmdroid** [IonicaBizau/anything-for-dummies#1]
If no text is inserted into the prompts, it will set the title and the link in the location.search to null.. That might be a small problem.

**Comment by IonicaBizau** [comment]
Well... _null for dummies_ doesn't sound so bad. Doesn't sound bad at all. :smile:

**Comment by IonicaBizau** [comment]
However, if like you can submit a pull request with a fix.

**Comment by IonicaBizau** [comment]
Fixed via #2. :clap: :+1:
